dependencies:
  '@rush-temp/my-app': 'file:projects/my-app.tgz'
  '@rush-temp/my-controls': 'file:projects/my-controls.tgz'
  '@rush-temp/my-toolchain': 'file:projects/my-toolchain.tgz'
  '@types/node': 10.14.5
  colors: 1.3.3
  rimraf: 2.6.3
  typescript: 3.4.5
  whatwg-fetch: 3.0.0
packages:
  /@types/node/10.14.5:
    dev: false
    resolution:
      integrity: sha512-Ja7d4s0qyGFxjGeDq5S7Si25OFibSAHUi6i17UWnwNnpitADN7hah9q0Tl25gxuV5R1u2Bx+np6w4LHXfHyj/g==
  /balanced-match/1.0.0:
    dev: false
    resolution:
      integrity: sha1-ibTRmasr7kneFk6gK4nORi1xt2c=
  /brace-expansion/1.1.11:
    dependencies:
      balanced-match: 1.0.0
      concat-map: 0.0.1
    dev: false
    resolution:
      integrity: sha512-iCuPHDFgrHX7H2vEI/5xpz07zSHB00TpugqhmYtVmMO6518mCuRMoOYFldEBl0g187ufozdaHgWKcYFb61qGiA==
  /colors/1.3.3:
    dev: false
    engines:
      node: '>=0.1.90'
    resolution:
      integrity: sha512-mmGt/1pZqYRjMxB1axhTo16/snVZ5krrKkcmMeVKxzECMMXoCgnvTPp10QgHfcbQZw8Dq2jMNG6je4JlWU0gWg==
  /concat-map/0.0.1:
    dev: false
    resolution:
      integrity: sha1-2Klr13/Wjfd5OnMDajug1UBdR3s=
  /fs.realpath/1.0.0:
    dev: false
    resolution:
      integrity: sha1-FQStJSMVjKpA20onh8sBQRmU6k8=
  /glob/7.1.3:
    dependencies:
      fs.realpath: 1.0.0
      inflight: 1.0.6
      inherits: 2.0.3
      minimatch: 3.0.4
      once: 1.4.0
      path-is-absolute: 1.0.1
    dev: false
    resolution:
      integrity: sha512-vcfuiIxogLV4DlGBHIUOwI0IbrJ8HWPc4MU7HzviGeNho/UJDfi6B5p3sHeWIQ0KGIU0Jpxi5ZHxemQfLkkAwQ==
  /inflight/1.0.6:
    dependencies:
      once: 1.4.0
      wrappy: 1.0.2
    dev: false
    resolution:
      integrity: sha1-Sb1jMdfQLQwJvJEKEHW6gWW1bfk=
  /inherits/2.0.3:
    dev: false
    resolution:
      integrity: sha1-Yzwsg+PaQqUC9SRmAiSA9CCCYd4=
  /minimatch/3.0.4:
    dependencies:
      brace-expansion: 1.1.11
    dev: false
    resolution:
      integrity: sha512-yJHVQEhyqPLUTgt9B83PXu6W3rx4MvvHvSUvToogpwoGDOUQ+yDrR0HRot+yOCdCO7u4hX3pWft6kWBBcqh0UA==
  /once/1.4.0:
    dependencies:
      wrappy: 1.0.2
    dev: false
    resolution:
      integrity: sha1-WDsap3WWHUsROsF9nFC6753Xa9E=
  /path-is-absolute/1.0.1:
    dev: false
    engines:
      node: '>=0.10.0'
    resolution:
      integrity: sha1-F0uSaHNVNP+8es5r9TpanhtcX18=
  /rimraf/2.6.3:
    dependencies:
      glob: 7.1.3
    dev: false
    hasBin: true
    resolution:
      integrity: sha512-mwqeW5XsA2qAejG46gYdENaxXjx9onRNCfn7L0duuP4hCuTIi/QO7PDK07KJfp1d+izWPrzEJDcSqBa0OZQriA==
  /typescript/3.4.5:
    dev: false
    engines:
      node: '>=4.2.0'
    hasBin: true
    resolution:
      integrity: sha512-YycBxUb49UUhdNMU5aJ7z5Ej2XGmaIBL0x34vZ82fn3hGvD+bgrMrVDpatgz2f7YxUMJxMkbWxJZeAvDxVe7Vw==
  /whatwg-fetch/3.0.0:
    dev: false
    resolution:
      integrity: sha512-9GSJUgz1D4MfyKU7KRqwOjXCXTqWdFNvEr7eUBYchQiVc744mqK/MzXPNR2WsPkmkOa4ywfg8C2n8h+13Bey1Q==
  /wrappy/1.0.2:
    dev: false
    resolution:
      integrity: sha1-tSQ9jz7BqjXxNkYFvA0QNuMKtp8=
  'file:projects/my-app.tgz':
    dependencies:
      typescript: 3.4.5
      whatwg-fetch: 3.0.0
    dev: false
    name: '@rush-temp/my-app'
    resolution:
      integrity: sha512-mi3UPHguYxx/Wzhcj7O+cepH+zxgIUil2JEQ8Fcb4TmcelePmwnPZmi9bUBnEeREizwws6+4dm2wsHo7K596ag==
      tarball: 'file:projects/my-app.tgz'
    version: 0.0.0
  'file:projects/my-controls.tgz':
    dependencies:
      typescript: 3.4.5
    dev: false
    name: '@rush-temp/my-controls'
    resolution:
      integrity: sha512-oHXOZCwlbGEILYNWY1vV0/W/Y9oPXB7r6QoLVZdUv/TZ20brYDtZ9/WIzqjN1YNUQRJpmtyyLxp/NAhM8tphBg==
      tarball: 'file:projects/my-controls.tgz'
    version: 0.0.0
  'file:projects/my-toolchain.tgz':
    dependencies:
      '@types/node': 10.14.5
      colors: 1.3.3
      rimraf: 2.6.3
      typescript: 3.4.5
    dev: false
    name: '@rush-temp/my-toolchain'
    resolution:
      integrity: sha512-6Yh2A6KCBSW0Y6ynP69hdpZnVtsq0oMxQBApV82kBgz9+ha3i/OcPq7PAp8/vs/xBGz1d2CfAc1+r0Ipi2M+zA==
      tarball: 'file:projects/my-toolchain.tgz'
    version: 0.0.0
registry: 'https://registry.npmjs.org/'
shrinkwrapMinorVersion: 9
shrinkwrapVersion: 3
specifiers:
  '@rush-temp/my-app': 'file:./projects/my-app.tgz'
  '@rush-temp/my-controls': 'file:./projects/my-controls.tgz'
  '@rush-temp/my-toolchain': 'file:./projects/my-toolchain.tgz'
  '@types/node': ^10.9.4
  colors: ^1.3.2
  rimraf: ^2.6.2
  typescript: ^3.0.3
  whatwg-fetch: ^3.0.0
