name: Build

on:
  push:
    branches: [master]
  workflow_dispatch:
    inputs:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/my-app
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Setup Node and NPM
        uses: volta-cli/action@v1
        with:
          node-version: 14.15.1

      - name: Cache pnpm modules
        uses: actions/cache@v2
        env:
          cache-name: cache-pnpm-modules
        with:
          path: common/temp/pnpm-store
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-

      - name: Install rush
        run: node common/scripts/install-run-rush.js install

      - name: Check CWD
        run: |
          echo $PWD
          ls
          pwd
